export const privacyEn = {
	label: 'Legal',
	title: 'Personal Data Processing Policy',
	last_updated: 'This version of the Policy takes effect on 13 July 2026.',
	meta_title: 'Personal Data Policy — {company}',
	meta_description:
		'Personal data processing policy of {company} — purposes, legal grounds, and data subject rights.',
	sections: [
		{
			title: '1. General Provisions',
			body: '1.1. This Personal Data Processing Policy (the "Policy") is developed by {company} in accordance with personal data protection legislation and constitutes one of the measures to protect personal data of users of the information resource {site} (the "Site"), as provided for in Article 17 of the Law of the Republic of Belarus No. 99-Z of 7 May 2021 "On Personal Data Protection" (the "Law").\n\n1.2. The Policy explains what personal data is processed, for what purposes, on what legal grounds, and what rights data subjects have and how to exercise them.\n\n1.3. The Policy applies to all users of the Site.\n\n1.4. "{company}" and "the Organization" refer to the {company} software development team based in {location}. You can contact the Organization via feedback forms on the Site, at {email}, or by phone: {phones}.\n\n1.5. The procedure and conditions for processing information from cookie files are defined in the Cookie Processing Policy.\n\n1.6. The Policy is always available on the Site. The Organization may amend the Policy at any time without prior notice. A new version takes effect upon publication on the Site unless the version itself provides otherwise.'
		},
		{
			title: '2. Procedure and Conditions for Personal Data Processing',
			body: '2.1. The Organization processes personal data based on the principles of lawfulness, fairness, transparency, purpose limitation, data minimization, accuracy, storage limitation, and appropriate security.\n\n2.2. The Organization processes personal data for the following purposes:\n— reviewing applications and enquiries submitted through forms on the Site;\n— communicating with users regarding services;\n— concluding and performing software development agreements;\n— ensuring the operation and security of the Site;\n— fulfilling obligations under the legislation of the Republic of Belarus.\n\n2.3. Categories of data subjects: Site visitors, persons who submit applications or enquiries, and representatives of clients and contractors.\n\n2.4. The list of processed personal data depends on the nature of interaction and may include: name, email address, phone number, company name, project details, and other data voluntarily provided by the user.\n\n2.5. Legal grounds for processing include: consent of the data subject; a contract or actions necessary for its conclusion; and other grounds provided for in Article 6 of the Law.\n\n2.6. Processing is carried out with and without automation. The Organization does not make decisions producing legal effects for the data subject solely on the basis of automated processing.\n\n2.7. Retention periods are determined by processing purposes and do not exceed what is necessary to achieve those purposes, unless a longer period is required by law. Application and correspondence data are generally retained for up to 3 years from the last interaction, unless otherwise agreed or required for contract performance.'
		},
		{
			title: '3. Authorized Persons. Disclosure to Third Parties',
			body: '3.1. The Organization may entrust personal data processing to authorized persons provided they comply with personal data legislation and contractual confidentiality and security obligations.\n\n3.2. To host and operate the Site, the Organization uses hosting and infrastructure services (including Cloudflare), to which a limited amount of technical data necessary for availability and security may be transferred.\n\n3.3. The Organization does not sell or transfer personal data to third parties for marketing purposes. Disclosure to public authorities occurs only as required by the legislation of the Republic of Belarus.\n\n3.4. When using email and messengers for communication, personal data may be processed by the operators of those services in accordance with their privacy policies.'
		},
		{
			title: '4. Cross-Border Transfer of Personal Data',
			body: '4.1. Due to the use of global cloud and infrastructure services, the Organization may transfer personal data cross-border to foreign states, including states that do not ensure an adequate level of protection of data subject rights.\n\n4.2. Cross-border transfer is carried out where legal grounds under Article 9 of the Law exist, including based on the data subject\'s consent or for contract performance.\n\n4.3. The Organization informs about risks associated with processing personal data in foreign jurisdictions, including differences in legal protection, access by law enforcement, and other risks provided for by the legislation of the Republic of Belarus.'
		},
		{
			title: '5. Data Subject Rights and How to Exercise Them',
			body: '5.1. A data subject has the right to:\n— receive information about the processing of their personal data;\n— request changes if data is incomplete, outdated, or inaccurate;\n— receive information about disclosure to third parties (once per calendar year);\n— request cessation of processing and deletion where no other legal grounds exist;\n— withdraw consent where processing is based on consent;\n— lodge a complaint with the National Personal Data Protection Centre.\n\n5.2. To exercise these rights, send a request to {email}. The request should include your name, contact details, the substance of your request, and a signature (for electronic documents — an electronic digital signature where applicable).\n\n5.3. The Organization reviews requests within time limits established by the legislation of the Republic of Belarus: generally up to 15 calendar days for requests to change, cease processing, or delete data; up to 5 business days to provide information about processing, unless other periods are set by law.\n\n5.4. A response is sent in the same form as the request unless the request specifies otherwise.\n\n5.5. For questions about personal data processing, contact the Organization at {email} or by phone: {phones}.'
		}
	]
} as const;
