-- +goose Up
-- +goose StatementBegin
-- Restore project display order from legacy Strapi (http://167.235.149.140:1337/projects).
-- Unique `url` in API response order (= sorting DESC with API tie-break).
-- Sets global_sort_order (portfolio "all") and sort_order within each category.

WITH ordered(slug, global_sort_order) AS (
  VALUES
  ('aifront-app', 0),
  ('aifront', 1),
  ('geopolia', 2),
  ('fcneman', 3),
  ('aigeneration', 4),
  ('corporate-website', 5),
  ('ott-ecosystem', 6),
  ('mylabel', 7),
  ('conceptfortheradiostation', 8),
  ('sportevent', 9),
  ('radioplayer-analytics', 10),
  ('radioplayer-stage5', 11),
  ('u-plast-analytics', 12),
  ('u-plast-app', 13),
  ('design-uplast', 14),
  ('gypsy', 15),
  ('sadik', 16),
  ('the-project', 17),
  ('theviewproperty', 18),
  ('tikoo-trade', 19),
  ('tikoo-market', 20),
  ('deck-tikoo', 21),
  ('newabff', 22),
  ('pflk-api', 23),
  ('pflk', 24),
  ('drawevent', 25),
  ('radioplayer-stage4', 26),
  ('radioplayer-stage3', 27),
  ('zero23', 28),
  ('radioplayer-stage2', 29),
  ('radioplayer-stage1', 30),
  ('unistar', 31),
  ('leasing-crm', 32),
  ('congruent', 33),
  ('finstore', 34),
  ('localmarket', 35),
  ('belint-new', 36),
  ('localstore', 37),
  ('rating', 38),
  ('alcohol-mockup', 39),
  ('pressball', 40),
  ('unitess', 41),
  ('fdc', 42),
  ('mexico', 43),
  ('theview', 44),
  ('weswim', 45),
  ('vebtech', 46),
  ('pal', 47),
  ('theview-lending', 48),
  ('rsm', 49),
  ('polimaster-new', 50),
  ('tvoydom', 51),
  ('centerfm', 52),
  ('airport', 53),
  ('abff-comet', 54),
  ('polimaster-promo', 55),
  ('redesign-humorfm', 56),
  ('gdrive', 57),
  ('voka-tv', 58),
  ('2gkb', 59),
  ('redesign-humorfmapp', 60),
  ('armtek-promo', 61),
  ('airon-redesign', 62),
  ('prosmartmovers', 63),
  ('bilet-vir-by-concept', 64),
  ('abff', 65),
  ('smartkarta', 66),
  ('funtastik', 67),
  ('bolshedrayva', 68),
  ('belintertrans', 69),
  ('fito', 70),
  ('geo', 71),
  ('bilet-vir-by', 72),
  ('dodoctor', 73),
  ('tehnobankblog', 74),
  ('malinovka', 75),
  ('horizont2', 76),
  ('bntd', 77),
  ('zolotayabochka', 78),
  ('orgpromstroy', 79),
  ('sontsa', 80),
  ('onega', 81),
  ('brest-litovsk', 82),
  ('callifornia', 83),
  ('avtoradio-app', 84),
  ('avtoradio', 85),
  ('radiusfm', 86),
  ('bnb', 87),
  ('kocmo', 88),
  ('parfumstandard', 89),
  ('humorfm', 90),
  ('trademebel', 91),
  ('v-tv-new', 92),
  ('humorfm-app', 93),
  ('emarkwin', 94),
  ('aps-concept-idea', 95),
  ('lidskae', 96),
  ('airon', 97),
  ('sportweek', 98),
  ('versusports', 99),
  ('versusports-app', 100),
  ('uplast-calculator', 101),
  ('detskidom', 102),
  ('polimaster', 103),
  ('molochnyymir', 104),
  ('radiorelax-app', 105),
  ('expobel', 106),
  ('radiorelax', 107),
  ('autoactive', 108),
  ('farmina-shop', 109),
  ('mini-mba', 110),
  ('addicted-agency', 111),
  ('factios', 112),
  ('v-tv', 113),
  ('vecherniy-grodno', 114),
  ('ecyberbet', 115),
  ('pg-arch', 116),
  ('aps-solver', 117),
  ('milkavita', 118),
  ('shef', 119),
  ('selfiest', 120),
  ('metallobaza-concept-idea', 121),
  ('selfiest-app', 122),
  ('horizont', 123),
  ('tekro', 124),
  ('satio', 125),
  ('travelspot', 126),
  ('univermag-belarus', 127),
  ('piplos2', 128),
  ('tabak', 129),
  ('marshallsmokers', 130),
  ('sankusm', 131),
  ('mehuborka', 132),
  ('almishop', 133),
  ('bellact', 134),
  ('artox-media', 135),
  ('edison', 136),
  ('piplos', 137),
  ('planeta-grioz', 138),
  ('lidskaya-muka', 139),
  ('chelobanov', 140),
  ('mbg', 141),
  ('nereida', 142),
  ('saleo', 143),
  ('bitva-pollov', 144),
  ('budutam', 145),
  ('trionis', 146),
  ('budutam-android', 147),
  ('beton-tvs', 148),
  ('promo-site-ren', 149),
  ('maldini', 150),
  ('tennis', 151),
  ('tontiag-app', 152),
  ('derevo-mechti', 153),
  ('geopromsk', 154),
  ('autoactive-site', 155),
  ('tvoydom-promo', 156),
  ('buyarearugs', 157),
  ('harmony', 158),
  ('jemchug', 159),
  ('active-life', 160),
  ('tontiag', 161),
  ('teos', 162),
  ('fotokonkurs-allo', 163),
  ('103by', 164),
  ('lifegadget', 165),
  ('brillianti-hyndai', 166),
  ('allo-fotokonkurs-vlublennih', 167),
  ('aplus', 168),
  ('favorit20', 169),
  ('csat', 170),
  ('noodlescity', 171),
  ('pismo-dedu-morozu', 172),
  ('port-aliance', 173),
  ('elithouse', 174),
  ('rasti', 175),
  ('farmina-promo', 176),
  ('zakatki-ren', 177),
  ('corado', 178),
  ('modnikov', 179),
  ('kalilaska', 180),
  ('site-igra-bandidos', 181),
  ('shootmemore', 182),
  ('orgpromstroy-concept', 183),
  ('shkodovody-belarusi', 184),
  ('soberi-devushku-na-vecherinku', 185),
  ('souser', 186),
  ('qcs', 187),
  ('ojoobo', 188),
  ('sta-logistic', 189),
  ('ulmus', 190),
  ('woman-calendar', 191),
  ('sugarmotel', 192),
  ('metallobaza', 193),
  ('dom', 194),
  ('souz-agro', 195),
  ('zhemchug', 196),
  ('lubimi-napitok-blondinki', 197),
  ('milalolcover3', 198),
  ('milalolcover2', 199),
  ('alniko', 200),
  ('milalolcover1', 201),
  ('francerdvcover2', 202),
  ('francerdvcover1', 203),
  ('shokozamok', 204),
  ('25-let-belita', 205),
  ('uznai-svoi-tip-vneshnosti', 206),
  ('fotokonkurs-belita', 207),
  ('viberi-svoi-ford', 208),
  ('viberi-svoi-opel', 209),
  ('viberi-svoi-auto', 210),
  ('vtbipad', 211),
  ('waysoflooking', 212),
  ('artinsheffield', 213),
  ('ultrabooksreview', 214),
  ('milalolcontest', 215),
  ('calendar-ren', 216)
)
UPDATE projects p
SET global_sort_order = o.global_sort_order,
    updated_at = now()
FROM ordered o
WHERE p.slug = o.slug;

UPDATE projects p
SET sort_order = s.rn,
    updated_at = now()
FROM (
  SELECT id,
         (ROW_NUMBER() OVER (PARTITION BY category ORDER BY global_sort_order) - 1)::int AS rn
  FROM projects
) s
WHERE p.id = s.id;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- Previous order is not restored; re-import from Strapi or restore a DB backup.
SELECT 1;
-- +goose StatementEnd
